//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defect_Tracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Defect_TrackerEntities1 : DbContext
    {
        public Defect_TrackerEntities1()
            : base("name=Defect_TrackerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<release> releases { get; set; }
        public virtual DbSet<Testexecution> Testexecutions { get; set; }
        public virtual DbSet<TicketInfo> TicketInfoes { get; set; }
        public virtual DbSet<Defect> Defects { get; set; }
    }
}
