//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defect_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public int D_id { get; set; }
        public Nullable<int> T_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public string d_number { get; set; }
        public string d_title { get; set; }
        public string D_Description { get; set; }
        public byte[] attachment { get; set; }
        public string Stepstorepro { get; set; }
    
        public virtual release release { get; set; }
    }
}
