//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defect_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testexecution
    {
        public int TE_Id { get; set; }
        public int T_Id { get; set; }
        public Nullable<int> Testcases { get; set; }
        public Nullable<int> passed { get; set; }
        public Nullable<int> fail { get; set; }
        public Nullable<int> onhold { get; set; }
        public Nullable<int> defects { get; set; }
        public string comments { get; set; }
    
        public virtual TicketInfo TicketInfo { get; set; }
    }
}
