//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defect_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketInfo()
        {
            this.Testexecutions = new HashSet<Testexecution>();
        }
    
        public int T_Id { get; set; }
        public Nullable<int> R_ID { get; set; }
        public string T_Number { get; set; }
        public string T_Desc { get; set; }
        public string T_State { get; set; }
        public string T_Developer { get; set; }
        public string T_Tester { get; set; }
    
        public virtual release release { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testexecution> Testexecutions { get; set; }
    }
}
